version: '3'
services:
  demo_app:
    container_name: demo_app
    build: ./src
    restart: always
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - ./src:/code
    command: flask run --host=0.0.0.0 --port 3000
